# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0002_auto_20180717_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='snap.Category'),
            preserve_default=False,
        ),
    ]
