# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_description',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
